// CREATE TABLE reconstruction, for the schema half of a SQL dump.
//
// MySQL can answer this exactly (`SHOW CREATE TABLE`), so the driver does it
// there. PostgreSQL has no such statement, so the definition is rebuilt from
// the same column metadata the Tables tab already reads. That reconstruction is
// deliberately limited to columns, defaults and the primary key: secondary
// indexes, foreign keys, checks and triggers are *not* in it. A dump that
// quietly claimed to be a full schema would be the dangerous version — so the
// dump header says so in as many words, and `synthesized` marks it here.
import { qMy, qPg } from '../drivers/identifiers.js';

/**
 * @param dialect 'MySQL' | 'MariaDB' | 'PostgreSQL'
 * @param table   table name (already validated by the caller)
 * @param info    from `fetchTableInfo`: columns[], primaryKey[]
 * @returns {{sql: string, synthesized: true}}
 */
export function createTableSQL(dialect, table, info) {
  const pg = dialect === 'PostgreSQL';
  const q = pg ? qPg : qMy;
  const cols = (info && info.columns) || [];
  if (!cols.length) {
    throw Object.assign(
      new Error('Struktur kolom tabel tidak terbaca, jadi CREATE TABLE tidak bisa dibuat. Pilih "hanya INSERT" untuk tetap mengekspor datanya.'),
      { expected: true }
    );
  }

  const lines = cols.map((c) => `  ${q(c.name)} ${columnClause(c, pg)}`);
  const pk = (info.primaryKey || []).filter((name) => cols.some((c) => c.name === name));
  if (pk.length) lines.push(`  PRIMARY KEY (${pk.map(q).join(', ')})`);

  // Plain CREATE TABLE, not IF NOT EXISTS: if the target already has a table by
  // this name, failing is the right outcome. `IF NOT EXISTS` would skip the
  // create and then load every row into whatever schema happens to be there.
  return {
    sql: `CREATE TABLE ${q(table)} (\n${lines.join(',\n')}\n);`,
    synthesized: true
  };
}

function columnClause(c, pg) {
  const parts = [c.type];

  // A serial/identity column's default is `nextval('t_id_seq')` — a sequence
  // that will not exist in the target database. Recreating it as an identity
  // column is what the author meant, and it is portable within Postgres.
  const isSequence = pg && /^nextval\(/i.test(String(c.default || ''));
  if (isSequence) parts.push('GENERATED BY DEFAULT AS IDENTITY');
  else if (c.default != null && !c.isGenerated) parts.push(`DEFAULT ${c.default}`);

  if (!c.nullable) parts.push('NOT NULL');
  return parts.join(' ');
}

/**
 * Statements that put a table's auto-numbering back where the data left it.
 *
 * A dump writes primary keys explicitly. MySQL takes that in stride — an
 * explicit id moves AUTO_INCREMENT along, and `SHOW CREATE TABLE` carries the
 * counter anyway. Postgres does not: after loading rows 1..900 the identity
 * sequence is still at 1, and the next INSERT anyone runs fails on a duplicate
 * key. Restoring that is the difference between a dump you can load and a dump
 * you can use.
 *
 * @returns {string[]} zero or more statements to run after the data
 */
export function sequenceResets(dialect, table, info) {
  if (dialect !== 'PostgreSQL') return [];

  return ((info && info.columns) || [])
    .filter((c) => c.isGenerated)
    .map((c) => {
      const seq = `pg_get_serial_sequence(${lit(qPg(table))}, ${lit(c.name)})`;
      // The WHERE guard makes this a no-op for a generated column that has no
      // sequence behind it (a computed column), instead of an error.
      return (
        `SELECT setval(${seq}, COALESCE((SELECT MAX(${qPg(c.name)}) FROM ${qPg(table)}), 1), true)\n` +
        `  WHERE ${seq} IS NOT NULL;`
      );
    });
}

/** A SQL string literal — these names are already validated identifiers. */
const lit = (s) => `'${String(s).replace(/'/g, "''")}'`;
